package com.example.reviewsite.demo;

import com.example.reviewsite.demo.models.Category;

import com.example.reviewsite.demo.models.Director;
import com.example.reviewsite.demo.models.Movie;
import com.example.reviewsite.demo.models.Star;
import com.example.reviewsite.demo.repository.CategoryRepository;
import com.example.reviewsite.demo.repository.DirectorRepository;
import com.example.reviewsite.demo.repository.MovieRepository;
import com.example.reviewsite.demo.repository.StarRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

@Component
public class Populator implements CommandLineRunner {

    @Resource
    private CategoryRepository categoryRepo;
    @Resource
    private DirectorRepository directorRepo;
    @Resource
    private StarRepository starRepo;
    @Resource
    private MovieRepository movieRepo;

    @Override
    public void run(String... args) throws Exception {

        Category phase1 = new Category("Phase One", "../images/phase1.jpg");
        Category phase2 = new Category("Phase Two", "../images/phase2.jpg");
        Category phase3 = new Category("Phase Three", "../images/phase3.jpg");
        categoryRepo.save(phase1);
        categoryRepo.save(phase2);
        categoryRepo.save(phase3);

        Director favreau = new Director("Jon", "Favreau");
        Director leterrier = new Director("Louis", "Leterrier");
        Director branagh = new Director("Kenneth", "Branagh");
        Director johnston = new Director("Joe", "Johnston");
        Director whedon = new Director("Joss", "Whedon");
        Director black = new Director("Shane", "Black");
        Director taylor = new Director("Alan", "Taylor");
        Director gunn = new Director("James", "Gunn");
        Director reed = new Director("Peyton", "Reed");
        Director russo = new Director("Anthony and Joe", "Russo");
        Director derrickson = new Director("Scott", "Derrickson");
        Director watts = new Director("Jon", "Watts");
        Director waititi = new Director("Taika", "Waititi");
        Director coogler = new Director("Ryan", "Coogler");
        Director boden = new Director("Anna", "Boden");
        Director shortland = new Director("Cate", "Shortland");
        directorRepo.save(favreau);
        directorRepo.save(leterrier);
        directorRepo.save(branagh);
        directorRepo.save(johnston);
        directorRepo.save(whedon);
        directorRepo.save(black);
        directorRepo.save(taylor);
        directorRepo.save(gunn);
        directorRepo.save(reed);
        directorRepo.save(russo);
        directorRepo.save(derrickson);
        directorRepo.save(watts);
        directorRepo.save(waititi);
        directorRepo.save(coogler);
        directorRepo.save(boden);
        directorRepo.save(shortland);

        Star rdj = new Star("Robert", "Downey Jr.", "../images/rdj.jpg");
        Star howard = new Star("Terrence", "Howard", "../images/howard.jpg");
        Star bridges = new Star("Jeff", "Bridges", "../images/bridges.jpg");
        Star paltrow = new Star("Gwyneth", "Paltrow", "../images/paltrow.jpg");
        Star gregg = new Star("Clark", "Gregg", "../images/gregg.jpg");
        Star bettany = new Star("Paul", "Bettany", "../images/bettany.jpg");
        Star norton = new Star("Edward", "Norton", "../images/norton.jpg");
        Star tyler = new Star("Liv", "Tyler", "../images/tyler.jpg");
        Star hurt = new Star("William", "Hurt", "../images/hurt.jpg");
        Star cheadle = new Star("Don", "Cheadle", "../images/cheadle.jpg");
        Star johansson = new Star("Scarlett", "Johansson", "../images/johansson.jpg");
        Star rourke = new Star("Mickey", "Rourke", "../images/rourke.jpg");
        Star hemsworth = new Star("Chris", "Hemsworth", "../images/hemsworth.jpg");
        Star portman = new Star("Natalie", "Portman", "../images/portman.jpg");
        Star hiddleston = new Star("Tom", "Hiddleston", "../images/hiddleston.jpg");
        Star hopkins = new Star("Anthony", "Hopkins", "../images/hopkins.jpg");
        Star skarsgard = new Star("Stellan", "Skarsgard", "../images/skarsgard.jpg");
        Star dennings = new Star("Kat", "Dennings", "../images/dennings.jpg");
        Star elba = new Star("Idris", "Elba", "../images/elba.jpg");
        Star evans = new Star("Chris", "Evans", "../images/evans.jpg");
        Star jones= new Star("Tommy Lee", "Jones", "../images/jones.jpg");
        Star weaving = new Star("Hugo", "Weaving", "../images/weaving.jpg");
        Star atwell = new Star("Hayley", "Atwell", "../images/atwell.jpg");
        Star stan = new Star("Sebastian", "Stan", "../images/stan.jpg");
        Star ruffalo = new Star("Mark", "Ruffalo", "../images/ruffalo.jpg");
        Star renner = new Star("Jeremy", "Renner", "../images/renner.jpg");
        Star jackson = new Star("Samuel L", "Jackson", "../images/jackson.jpg");
        Star pearce = new Star("Guy", "Pearce", "../images/pearce.jpg");
        Star favreau2 = new Star("Jon", "Favreau", "../images/favreau.jpg");
        Star kingsley = new Star("Ben", "Kingsley", "../images/kingsley.jpg");
        Star pratt = new Star("Chris", "Pratt", "../images/pratt.jpg");
        Star saldana = new Star("Zoe", "Saldana", "../images/saldana.jpg");
        Star bautista = new Star("Dave", "Bautista", "../images/bautista.jpg");
        Star diesel = new Star("Vin", "Diesel", "../images/diesel.jpg");
        Star cooper = new Star("Bradley", "Cooper", "../images/cooper.jpg");
        Star pace = new Star("Lee", "Pace", "../images/pace.jpg");
        Star reily = new Star("John C", "Reily", "../images/reily.jpg");
        Star spader = new Star("James", "Spader", "../images/spader.jpg");
        Star rudd = new Star("Paul", "Rudd", "../images/rudd.jpg");
        Star lilly = new Star("Evangeline", "Lilly", "../images/lilly.jpg");
        Star stoll = new Star("Corey", "Stoll", "../images/stoll.jpg");
        Star douglas = new Star("Michael", "Douglas", "../images/douglas.jpg");
        Star mackie = new Star("Anthony", "Mackie", "../images/mackie.jpg");
        Star boseman = new Star("Chadwick", "Boseman", "../images/boseman.jpg");
        Star olsen = new Star("Elizabeth", "Olsen", "../images/olsen.jpg");
        Star holland = new Star("Tom", "Holland", "../images/holland.jpg");
        Star cumberbatch = new Star("Benedict", "Cumberbatch", "../images/cumberbatch.jpg");
        Star ejiofor = new Star("Chiwetel", "Ejiofor", "../images/ejiofor.jpg");
        Star mcadams = new Star("Rachel", "McAdams", "../images/mcadams.jpg");
        Star wong = new Star("Benedict", "Wong", "../images/wong.jpg");
        Star mikkelsen = new Star("Mads", "Mikkelsen", "../images/mikkelsen.jpg");
        Star swinton = new Star("Tilda", "Swinton", "../images/swinton.jpg");
        Star russell = new Star("Kurt", "Russel", "../images/russel.jpg");
        Star keaton = new Star("Michael", "Keaton", "../images/keaton.jpg");
        Star zendaya = new Star("Zendaya", "Coleman", "../images/zendaya.jpg");
        Star glover = new Star("Donald", "Glover", "../images/glover.jpg");
        Star tomei = new Star("Marisa", "Tomei", "../images/howard.jpg");
        Star blanchett = new Star("Cate", "Blanchett", "../images/blanchett.jpg");
        Star goldblum = new Star("Jeff", "Goldblum", "../images/goldblum.jpg");
        Star jordan = new Star("Michael B", "Jordan", "../images/jordan.jpg");
        Star nyongo = new Star("Lupita", "Nyong'o", "../images/nyong'o.jpg");
        Star gurira = new Star("Danai", "Gurira", "../images/gurira.jpg");
        Star freeman = new Star("Martin", "Freeman", "../images/freeman.jpg");
        Star whitaker = new Star("Forest", "Whitaker", "../images/whitaker.jpg");
        Star brolin = new Star("Josh", "Brolin", "../images/brolin.jpg");
        Star pena = new Star("Michael", "Pena", "../images/pena.jpg");
        Star pfeiffer = new Star("Michelle", "Pfeiffer", "../images/pfeiffer.jpg");
        Star larson = new Star("Brie", "Larson", "../images/larson.jpg");
        Star mendelsohn = new Star("Ben", "Mendelsohn", "../images/mendelsohn.jpg");
        Star hounsou = new Star("Djimon", "Hounsou", "../images/hounsou.jpg");
        Star lynch = new Star("Lashana", "Lynch", "../images/lynch.jpg");
        Star law = new Star("Jude", "Law", "../images/law.jpg");
        Star bening = new Star("Annette", "Bening", "../images/bening.jpg");
        Star smulders = new Star("Cobie", "Smulders", "../images/smulders.jpg");
        Star gyllenhaal = new Star("Jake", "Gyllenhaal", "../images/gyllenhaal.jpg");
        Star gillan = new Star("Karen", "Gillan", "../images/gillan.jpg");
        starRepo.save(rdj);
        starRepo.save(howard);
        starRepo.save(bridges);
        starRepo.save(paltrow);
        starRepo.save(gregg);
        starRepo.save(bettany);
        starRepo.save(norton);
        starRepo.save(tyler);
        starRepo.save(hurt);
        starRepo.save(cheadle);
        starRepo.save(johansson);
        starRepo.save(rourke);
        starRepo.save(hemsworth);
        starRepo.save(portman);
        starRepo.save(hiddleston);
        starRepo.save(hopkins);
        starRepo.save(skarsgard);
        starRepo.save(dennings);
        starRepo.save(elba);
        starRepo.save(evans);
        starRepo.save(jones);
        starRepo.save(weaving);
        starRepo.save(atwell);
        starRepo.save(stan);
        starRepo.save(ruffalo);
        starRepo.save(renner);
        starRepo.save(jackson);
        starRepo.save(pearce);
        starRepo.save(favreau2);
        starRepo.save(kingsley);
        starRepo.save(pratt);
        starRepo.save(saldana);
        starRepo.save(bautista);
        starRepo.save(diesel);
        starRepo.save(cooper);
        starRepo.save(pace);
        starRepo.save(reily);
        starRepo.save(spader);
        starRepo.save(rudd);
        starRepo.save(lilly);
        starRepo.save(stoll);
        starRepo.save(douglas);
        starRepo.save(mackie);
        starRepo.save(boseman);
        starRepo.save(olsen);
        starRepo.save(holland);
        starRepo.save(cumberbatch);
        starRepo.save(ejiofor);
        starRepo.save(mcadams);
        starRepo.save(wong);
        starRepo.save(mikkelsen);
        starRepo.save(swinton);
        starRepo.save(russell);
        starRepo.save(keaton);
        starRepo.save(zendaya);
        starRepo.save(glover);
        starRepo.save(tomei);
        starRepo.save(blanchett);
        starRepo.save(goldblum);
        starRepo.save(jordan);
        starRepo.save(nyongo);
        starRepo.save(gurira);
        starRepo.save(freeman);
        starRepo.save(whitaker);
        starRepo.save(brolin);
        starRepo.save(pena);
        starRepo.save(pfeiffer);
        starRepo.save(larson);
        starRepo.save(mendelsohn);
        starRepo.save(hounsou);
        starRepo.save(lynch);
        starRepo.save(law);
        starRepo.save(bening);
        starRepo.save(smulders);
        starRepo.save(gyllenhaal);
        starRepo.save(gillan);

        Movie ironMan = new Movie("Iron Man", "../images/iron_man.jpg", favreau, phase1, "2008", "review", rdj, howard, bridges, paltrow, gregg, bettany, favreau2);
        Movie theIncredibleHulk = new Movie("The Incredible Hulk", "../images/incredible_hulk.jpg", leterrier, phase1, "2008", "review", norton, tyler, hurt);
        Movie ironMan2 = new Movie("Iron Man 2", "../images/iron_man_2.jpg", favreau, phase1, "2010", "review", rdj, paltrow, cheadle, johansson, rourke, jackson, gregg, bettany, favreau2);
        Movie thor = new Movie("Thor", "../images/thor.jpg", branagh, phase1, "2011", "review", hemsworth, portman, hiddleston, hopkins, skarsgard, dennings, gregg, elba);
        Movie captainAmerica = new Movie("Captain America: The First Avenger", "../images/captain_america.jpg", johnston, phase1, "2011", "review", evans, atwell, stan, jones, weaving, jackson);
        Movie avengers = new Movie("The Avengers", "../images/avengers.jpg", whedon, phase1, "2012", "review", rdj, evans, ruffalo, hemsworth, johansson, renner, hiddleston, gregg, skarsgard, smulders, jackson, paltrow, bettany);
        Movie ironMan3 = new Movie("Iron Man 3", "../images/iron_man_3.jpg", black, phase2, "2013", "review",rdj, paltrow, cheadle, pearce, favreau2, kingsley, bettany);
        Movie thor2 = new Movie("Thor: The Dark World", "../images/thor_2.jpg", taylor, phase2, "2013", "review", hemsworth, portman, hiddleston, hopkins, elba, dennings, skarsgard);
        Movie captainAmerica2 = new Movie("Captain America: Winter Soldier", "../images/captain_america_2.jpg", russo, phase2, "2014", "review", evans, jackson, johansson, stan, mackie, smulders);
        Movie guardians = new Movie("Guardians of the Galaxy", "../images/guardians.jpg", gunn, phase2, "2014", "review", pratt, saldana, bautista, diesel, cooper, pace, reily, gillan);
        Movie avengers2 = new Movie("Avengers: Age of Ultron", "../images/age_of_ultron.jpg", whedon, phase2, "2015", "review", rdj, hemsworth, ruffalo, evans, johansson, renner, spader, jackson, cheadle, olsen, bettany, smulders, mackie, atwell, elba, skarsgard);
        Movie antMan = new Movie("Ant-Man", "../images/ant-man.jpg", reed, phase2, "2015", "review", rudd, douglas, lilly, stoll, mackie, pena, atwell);
        Movie captainAmerica3 = new Movie("Captain America: Civil War", "../images/civil war.jpg", russo, phase3, "2016", "review", evans, rdj, johansson, stan, mackie, cheadle, renner, boseman, bettany, olsen, rudd, holland, hurt, freeman, tomei);
        Movie doctorStrange = new Movie("Doctor Strange", "../images/doctor_strange.jpg", derrickson, phase3, "2016", "review", cumberbatch, ejiofor, mcadams, wong, swinton, mikkelsen);
        Movie guardians2 = new Movie("Guardians of the Galaxy Vol 2", "../images/guardians_vol2.jpg", gunn, phase3, "2017", "review", pratt, saldana, bautista, diesel, cooper, russell, gillan);
        Movie spiderMan = new Movie("Spider-Man: Homecoming", "../images/spider-man_homecoming.jpg", watts, phase3, "2017", "review", holland, keaton, rdj, tomei, favreau2, paltrow, zendaya, glover);
        Movie thor3 = new Movie("Thor: Ragnarok", "../images/thor_3.jpg", waititi, phase3, "2017", "review", hemsworth, hiddleston, blanchett, elba, goldblum, ruffalo, hopkins, cumberbatch);
        Movie blackPanther = new Movie("Black Panther", "../images/black panther.jpg", coogler, phase3, "2018", "review", boseman, jordan, nyongo, gurira, freeman, whitaker);
        Movie avengers3 = new Movie("Avengers: Infinity War", "../images/avengers_infinity_war.jpg", russo, phase3, "2018", "review", rdj, hemsworth, ruffalo, evans, johansson, cheadle, cumberbatch, holland, boseman, saldana, hiddleston, bettany, olsen, mackie, stan, elba, gurira, wong, bautista, diesel, cooper, paltrow, brolin, pratt, hurt, gillan);
        Movie antMan2 = new Movie("Ant-Man and the Wasp", "../images/ant-man_the-wasp.jpg", reed, phase3, "2018", "review", rudd, lilly, pena, pfeiffer, douglas);
        Movie captainMarvel = new Movie("Captain Marvel", "../images/captain_marvel.jpg", boden, phase3, "2019", "review", larson, jackson, mendelsohn, law, bening, hounsou, pace, lynch);
        Movie avengers4 = new Movie("Avengers: Endgame", "../images/endgame.jpg", russo, phase3, "2019", "review", rdj, evans, ruffalo, hemsworth, johansson, renner, cheadle, rudd, cumberbatch, boseman, larson, holland, saldana, lilly, olsen, mackie, stan, hiddleston, gurira, wong, bautista, swinton, favreau2, atwell, portman, tomei, douglas, pfeiffer, hurt, smulders, diesel, cooper, paltrow, brolin, pratt, jackson, gillan);
        Movie spiderMan2 = new Movie("Spider-Man: Far From Home", "../images/spider-man_far_from_home.jpg", watts, phase3, "2019", "review", holland, jackson, gyllenhaal, tomei, favreau2, zendaya);
        Movie blackWidow = new Movie("Black Widow", "../images/black_widow.jpg", shortland, phase3, "2012", "review", johansson, hurt);
        movieRepo.save(ironMan);
        movieRepo.save(theIncredibleHulk);
        movieRepo.save(ironMan2);
        movieRepo.save(thor);
        movieRepo.save(captainAmerica);
        movieRepo.save(avengers);
        movieRepo.save(ironMan3);
        movieRepo.save(thor2);
        movieRepo.save(captainAmerica2);
        movieRepo.save(guardians);
        movieRepo.save(avengers2);
        movieRepo.save(antMan);
        movieRepo.save(captainAmerica3);
        movieRepo.save(doctorStrange);
        movieRepo.save(guardians2);
        movieRepo.save(spiderMan);
        movieRepo.save(thor3);
        movieRepo.save(blackPanther);
        movieRepo.save(avengers3);
        movieRepo.save(antMan2);
        movieRepo.save(captainMarvel);
        movieRepo.save(avengers4);
        movieRepo.save(spiderMan2);
        movieRepo.save(blackWidow);
    }
}
