package com.example.reviewsite.demo;

import com.example.reviewsite.demo.models.Category;

import com.example.reviewsite.demo.models.Director;
import com.example.reviewsite.demo.models.Movie;
import com.example.reviewsite.demo.models.Star;
import com.example.reviewsite.demo.repository.CategoryRepository;
import com.example.reviewsite.demo.repository.DirectorRepository;
import com.example.reviewsite.demo.repository.MovieRepository;
import com.example.reviewsite.demo.repository.StarRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

@Component
public class Populator implements CommandLineRunner {

    @Resource
    private CategoryRepository categoryRepo;
    @Resource
    private DirectorRepository directorRepo;
    @Resource
    private StarRepository starRepo;
    @Resource
    private MovieRepository movieRepo;

    @Override
    public void run(String... args) throws Exception {

        Category phase1 = new Category("Phase One", "../images/phase1.jpg");
        Category phase2 = new Category("Phase Two", "../images/phase2.jpg");
        Category phase3 = new Category("Phase Three", "../images/phase3.jpg");
        categoryRepo.save(phase1);
        categoryRepo.save(phase2);
        categoryRepo.save(phase3);

        Director favreau = new Director("Jon", "Favreau", "../images/favreau.jpg");
        Director leterrier = new Director("Louis", "Leterrier", "../images/leterrier.jpg");
        Director branagh = new Director("Kenneth", "Branagh", "../images/branagh.jpg");
        Director johnston = new Director("Joe", "Johnston", "../images/johnston.jpg");
        Director whedon = new Director("Joss", "Whedon", "../images/whedon.jpg");
        Director black = new Director("Shane", "Black", "../images/black.jpg");
        Director taylor = new Director("Alan", "Taylor", "../images/taylor.jpg");
        Director gunn = new Director("James", "Gunn", "../images/gunn.jpg");
        Director reed = new Director("Peyton", "Reed", "../images/reed.jpg");
        Director russo = new Director("Anthony and Joe", "Russo", "../images/russo.jpg");
        Director derrickson = new Director("Scott", "Derrickson", "../images/derrickson.jpg");
        Director watts = new Director("Jon", "Watts", "../images/watts.jpg");
        Director waititi = new Director("Taika", "Waititi", "../images/waititi.jpg");
        Director coogler = new Director("Ryan", "Coogler", "../images/coogler.jpg");
        Director boden = new Director("Anna", "Boden", "../images/boden.jpg");
        Director shortland = new Director("Cate", "Shortland", "../images/shortland.jpg");
        directorRepo.save(favreau);
        directorRepo.save(leterrier);
        directorRepo.save(branagh);
        directorRepo.save(johnston);
        directorRepo.save(whedon);
        directorRepo.save(black);
        directorRepo.save(taylor);
        directorRepo.save(gunn);
        directorRepo.save(reed);
        directorRepo.save(russo);
        directorRepo.save(derrickson);
        directorRepo.save(watts);
        directorRepo.save(waititi);
        directorRepo.save(coogler);
        directorRepo.save(boden);
        directorRepo.save(shortland);

        Star downey = new Star("Robert", "Downey Jr.", "../images/rdj.jpg", "https://www.youtube.com/embed/osSJhXruEzU");
        Star howard = new Star("Terrence", "Howard", "../images/howard.jpg", "https://www.youtube.com/embed/CwiaIbKXT50");
        Star bridges = new Star("Jeff", "Bridges", "../images/bridges.jpg", "https://www.youtube.com/embed/BKijvvTTZWU");
        Star paltrow = new Star("Gwyneth", "Paltrow", "../images/paltrow.jpg", "https://www.youtube.com/embed/PX35zJ4PBc8");
        Star gregg = new Star("Clark", "Gregg", "../images/gregg.jpg", "https://www.youtube.com/embed/yiSxjChrdMA");
        Star bettany = new Star("Paul", "Bettany", "../images/bettany.jpg", "https://www.youtube.com/embed/xFrkslYAVdI");
        Star norton = new Star("Edward", "Norton", "../images/norton.jpg", "https://www.youtube.com/embed/euxfiHgrsf0");
        Star tyler = new Star("Liv", "Tyler", "../images/tyler.jpg", "https://www.youtube.com/embed/euxfiHgrsf0");
        Star hurt = new Star("William", "Hurt", "../images/hurt.jpg", "https://www.youtube.com/embed/zP-C4hgT2JQ");
        Star cheadle = new Star("Don", "Cheadle", "../images/cheadle.jpg", "https://www.youtube.com/embed/CvmdXXrPy7U");
        Star johansson = new Star("Scarlett", "Johansson", "../images/johansson.jpg", "https://www.youtube.com/embed/UcswTPp4xqE");
        Star rourke = new Star("Mickey", "Rourke", "../images/rourke.jpg", "https://www.youtube.com/embed/ByoLiamWsUQ");
        Star hemsworth = new Star("Chris", "Hemsworth", "../images/hemsworth.jpg", "https://www.youtube.com/embed/Z68MRjRpwdo");
        Star portman = new Star("Natalie", "Portman", "../images/portman.jpg", "https://www.youtube.com/embed/f6NnvZNBM3I");
        Star hiddleston = new Star("Tom", "Hiddleston", "../images/hiddleson.jpg", "https://www.youtube.com/embed/qU58AtOuUd0");
        Star hopkins = new Star("Anthony", "Hopkins", "../images/hopkins.jpg", "https://www.youtube.com/embed/WM_VlwScjwo");
        Star skarsgard = new Star("Stellan", "Skarsgard", "../images/skarsgard.jpg", "https://www.youtube.com/embed/DTao7ANBXfk");
        Star dennings = new Star("Kat", "Dennings", "../images/dennings.jpg", "https://www.youtube.com/embed/4iu5pzgV8iA");
        Star elba = new Star("Idris", "Elba", "../images/elba.jpg", "https://www.youtube.com/embed/cZXjQee9VA4");
        Star evans = new Star("Chris", "Evans", "../images/evans.jpg", "https://www.youtube.com/embed/C2Qsh-R4a1k");
        Star jones= new Star("Tommy Lee", "Jones", "../images/jones.jpg", "https://www.youtube.com/embed/tIBwC-EIwRg");
        Star weaving = new Star("Hugo", "Weaving", "../images/weaving.jpg", "https://www.youtube.com/embed/KyEDA0f2MzA");
        Star atwell = new Star("Hayley", "Atwell", "../images/atwell.jpg", "https://www.youtube.com/embed/oQOhi0DG1Ag");
        Star stan = new Star("Sebastian", "Stan", "../images/stan.jpg", "https://www.youtube.com/embed/7g3Q8kHof8w");
        Star ruffalo = new Star("Mark", "Ruffalo", "../images/ruffalo.jpg", "https://www.youtube.com/embed/kO5WPKT0690");
        Star renner = new Star("Jeremy", "Renner", "../images/renner.jpg", "https://www.youtube.com/embed/2Kr_fw9LklA");
        Star jackson = new Star("Samuel L", "Jackson", "../images/jackson.jpg", "https://www.youtube.com/embed/JxVVaTXr4FM");
        Star pearce = new Star("Guy", "Pearce", "../images/pearce.jpg", "https://www.youtube.com/embed/Jef6OEBXl7w");
        Star favreau2 = new Star("Jon", "Favreau", "../images/favreau.jpg", "https://www.youtube.com/embed/tqmJjzS89H4");
        Star kingsley = new Star("Ben", "Kingsley", "../images/kingsley.jpg", "https://www.youtube.com/embed/2N7gVS_0f0E");
        Star pratt = new Star("Chris", "Pratt", "../images/pratt.jpg", "https://www.youtube.com/embed/ZQpWRenGF_w");
        Star saldana = new Star("Zoe", "Saldana", "../images/saldana.jpg", "https://www.youtube.com/embed/kMnQs4YIQmM");
        Star bautista = new Star("Dave", "Bautista", "../images/bautista.jpg", "https://www.youtube.com/embed/EIM78NrhixA");
        Star diesel = new Star("Vin", "Diesel", "../images/diesel.jpg", "https://www.youtube.com/embed/ALgf-uV1l_k");
        Star cooper = new Star("Bradley", "Cooper", "../images/cooper.jpg", "https://www.youtube.com/embed/hF1SVNYs23U");
        Star pace = new Star("Lee", "Pace", "../images/pace.jpg", "https://www.youtube.com/embed/MI5Pld2M-Ck");
        Star reily = new Star("John C", "Reily", "../images/reily.jpg", "https://www.youtube.com/embed/TW19M3VCeWc");
        Star spader = new Star("James", "Spader", "../images/spader.jpg", "https://www.youtube.com/embed/CxDQh_-vJss");
        Star rudd = new Star("Paul", "Rudd", "../images/rudd.jpg", "https://www.youtube.com/embed/OFqRej80iIY");
        Star lilly = new Star("Evangeline", "Lilly", "../images/lilly.jpg", "https://www.youtube.com/embed/m1z8hujJi0w");
        Star stoll = new Star("Corey", "Stoll", "../images/stoll.jpg", "https://www.youtube.com/embed/Zn9ct6cRUXU");
        Star douglas = new Star("Michael", "Douglas", "../images/douglas.jpg", "https://www.youtube.com/embed/uaz6nxyQA28");
        Star mackie = new Star("Anthony", "Mackie", "../images/mackie.jpg", "https://www.youtube.com/embed/ZOWZgkpnmuI");
        Star boseman = new Star("Chadwick", "Boseman", "../images/boseman.jpg", "https://www.youtube.com/embed/xx7afHUuREY");
        Star olsen = new Star("Elizabeth", "Olsen", "../images/olsen.jpg", "https://www.youtube.com/embed/14qmIBsdt6U");
        Star holland = new Star("Tom", "Holland", "../images/holland.jpg", "https://www.youtube.com/embed/r8-BFx3xFJ4");
        Star cumberbatch = new Star("Benedict", "Cumberbatch", "../images/cumberbatch.jpg", "https://www.youtube.com/embed/KpaHWMqAM0Y");
        Star ejiofor = new Star("Chiwetel", "Ejiofor", "../images/ejiofor.jpg", "https://www.youtube.com/embed/iRyNUqvP6vg");
        Star mcadams = new Star("Rachel", "McAdams", "../images/mcadams.jpg", "https://www.youtube.com/embed/zGzxJL-xCyA");
        Star wong = new Star("Benedict", "Wong", "../images/wong.jpg", "https://www.youtube.com/embed/slubggR1WLU");
        Star mikkelsen = new Star("Mads", "Mikkelsen", "../images/mikkelsen.jpg", "https://www.youtube.com/embed/_aJtQe5wn2g");
        Star swinton = new Star("Tilda", "Swinton", "../images/swinton.jpg", "https://www.youtube.com/embed/TFgmDlX5g3I");
        Star russell = new Star("Kurt", "Russel", "../images/russel.jpg", "https://www.youtube.com/embed/ZH-ArwwCK3s");
        Star keaton = new Star("Michael", "Keaton", "../images/keaton.jpg", "https://www.youtube.com/embed/_sHXbqFJCr0");
        Star zendaya = new Star("Zendaya", "Coleman", "../images/zendaya.jpg", "https://www.youtube.com/embed/zErzJxN84iw");
        Star glover = new Star("Donald", "Glover", "../images/glover.jpg", "https://www.youtube.com/embed/umcyzRBeJtE");
        Star tomei = new Star("Marisa", "Tomei", "../images/tomei.jpg", "https://www.youtube.com/embed/oCkUyjaZuNI");
        Star blanchett = new Star("Cate", "Blanchett", "../images/blanchett.jpg", "https://www.youtube.com/embed/Mv3-G1k8VFY");
        Star goldblum = new Star("Jeff", "Goldblum", "../images/goldblum.jpg", "https://www.youtube.com/embed/BhGvdT1n0Lc");
        Star jordan = new Star("Michael B", "Jordan", "../images/jordan.jpg", "https://www.youtube.com/embed/q_ngDuZaJqo");
        Star nyongo = new Star("Lupita", "Nyong'o", "../images/nyong'o.jpg", "https://www.youtube.com/embed/htdN2_9qq8s");
        Star gurira = new Star("Danai", "Gurira", "../images/gurira.jpg", "https://www.youtube.com/embed/Zm95JNgwz3c");
        Star freeman = new Star("Martin", "Freeman", "../images/freeman.jpg", "https://www.youtube.com/embed/1crJt8fC8_s");
        Star whitaker = new Star("Forest", "Whitaker", "../images/whitaker.jpg", "https://www.youtube.com/embed/enmdum3OUlM");
        Star brolin = new Star("Josh", "Brolin", "../images/brolin.jpg", "https://www.youtube.com/embed/XpeOIww_l4A");
        Star pena = new Star("Michael", "Pena", "../images/pena.jpg", "https://www.youtube.com/embed/iERODinkCFE");
        Star pfeiffer = new Star("Michelle", "Pfeiffer", "../images/pfeiffer.jpg", "https://www.youtube.com/embed/Q3PRxG8SYA4");
        Star larson = new Star("Brie", "Larson", "../images/larson.jpg", "https://www.youtube.com/embed/bA6houNQSZI");
        Star mendelsohn = new Star("Ben", "Mendelsohn", "../images/mendelsohn.jpg", "https://www.youtube.com/embed/HW-iFGIpAJw");
        Star hounsou = new Star("Djimon", "Hounsou", "../images/hounsou.jpg", "https://www.youtube.com/embed/jzhHy3qp7P8");
        Star lynch = new Star("Lashana", "Lynch", "../images/lynch.jpg", "https://www.youtube.com/embed/QDs2M3NiFi4");
        Star law = new Star("Jude", "Law", "../images/law.jpg", "https://www.youtube.com/embed/q-NAW3TaOxk");
        Star bening = new Star("Annette", "Bening", "../images/bening.jpg", "https://www.youtube.com/embed/wu16V0YTaHk");
        Star smulders = new Star("Cobie", "Smulders", "../images/smulders.jpg", "https://www.youtube.com/embed/DS3k6VLcrM8");
        Star gyllenhaal = new Star("Jake", "Gyllenhaal", "../images/gyllenhaal.jpg", "https://www.youtube.com/embed/q9X6tpvxZyE");
        Star gillan = new Star("Karen", "Gillan", "../images/gillan.jpg", "https://www.youtube.com/embed/IZ-1vORwhlk");
        Star bibb = new Star("Leslie", "Bibb", "../images/bibb.jpg", "");
        Star toub = new Star("Shaun", "Toub", "../images/toub.jpg", "");
        Star tahir = new Star("Faran", "Tahir", "../images/tahir.jpg", "");
        Star badreya = new Star("Sayed", "Badreya", "../images/badreya.jpg", "");
        Star guinee = new Star("Tim", "Guinee", "../images/guinee.jpg", "");
        Star roth = new Star("Tim", "Roth", "../images/roth.jpg", "");
        Star nelson = new Star("Tim Blake", "Nelson", "../images/nelson.jpg", "");
        Star burrell = new Star("Ty", "Burrell", "../images/burrell.jpg", "");
        Star ferrigno = new Star("Lou", "Ferrigno", "../images/ferrigno.jpg", "");
        Star lee = new Star("Stan", "Lee", "", "../images/lee.jpg");
        Star rockwell = new Star("Sam", "Rockwell", "../images/rockwell.jpg", "");
        Star slattery = new Star("John", "Slattery", "../images/slattery.jpg", "");
        Star shandling = new Star("Gary", "Shandling", "../images/shandling.jpg", "");
        Star feore = new Star("Colm", "Feore", "../images/feore.jpg", "");
        Star stevenson = new Star("Ray", "Stevenson", "../images/stevenson.jpg", "");
        Star asano = new Star("Tadanobu", "Asano", "../images/asano.jpg", "");
        Star dallas = new Star("Josh", "Dallas", "../images/dallas.jpg", "");
        Star alexander = new Star("Jaimie", "Alexander", "../images/alexander.jpg", "");
        Star cooper2 = new Star("Dominic", "Cooper", "../images/cooper2.jpg", "");
        Star armitage = new Star("Richard", "Armitage", "../images/armitage.jpg", "");
        Star tucci = new Star("Stanley", "Tucci", "../images/tucci.jpg", "");
        Star jones2 = new Star("Tobey", "Jones", "../images/jones2.jpg", "");
        Star mcdonough = new Star("Neal", "McDonough", "../images/mcdonough.jpg", "");
        Star luke = new Star("Derek", "Luke", "../images/luke.jpg", "");
        Star choi = new Star("Kenneth", "Choi", "../images/choi.jpg", "");
        Star hall = new Star("Rebecca", "Hall", "../images/hall.jpg", "");
        Star dale = new Star("James", "Badge Dale", "../images/dale.jpg", "");
        Star eccleston = new Star("Christopher", "Eccleston", "../images/eccleston.jpg", "");
        Star levi = new Star("Zachary", "Levi", "../images/levi.jpg", "");
        Star russo2 = new Star("Rene", "Russo", "../images/russo2.jpg", "");
        Star redford = new Star("Robert", "Redford", "../images/redford.jpg", "");
        Star grillo = new Star("Frank", "Grillo", "../images/grillo.jpg", "");
        Star vancamp = new Star("Emily", "VanCamp", "../images/vancamp.jpg", "");
        Star hernandez = new Star("Maximiliano", "Hernandez", "../images/hernandez.jpg", "");
        Star rooker = new Star("Michael", "Rooker", "../images/rooker.jpg", "");
        Star close = new Star("Glenn", "Close", "../images/close.jpg", "");
        Star toro = new Star("Benicio", "Del Toro", "../images/toro.jpg", "");
        Star haddock = new Star("Laura", "Haddock", "../images/haddock.jpg", "");
        Star gunn2 = new Star("Sean", "Gunn", "../images/gunn2.jpg", "");
        Star johnson = new Star("Aaron", "Taylor-Johnson", "../images/johnson.jpg", "");
        Star cardellini = new Star("Linda", "Cardellini", "../images/cardellini.jpg", "");
        Star serkis = new Star("Andy", "Serkis", "../images/serkis.jpg", "");
        Star cannavale = new Star("Bobby", "Cannavale", "../images/cannavale.jpg", "");
        Star greer = new Star("Judy", "Greer", "../images/greer.jpg", "");
        Star fortson = new Star("Abby", "Ryder Fortson", "../images/fortson.jpg", "");
        Star bruhl = new Star("Daniel", "Bruhl", "../images/bruhl.jpg", "");
        Star kani = new Star("John", "Kani", "../images/kani.jpg", "");
        Star davis = new Star("Hope", "Davis", "../images/davis.jpg", "");
        Star klementieff = new Star("Pom", "Klementieff", "../images/klementieff.jpg", "");
        Star stallone = new Star("Sylvester", "Stallone", "../images/stallone.jpg", "");
        Star debicki = new Star("Elizabeth", "Debicki", "../images/debicki.jpg", "");

        starRepo.save(downey);
        starRepo.save(howard);
        starRepo.save(bridges);
        starRepo.save(paltrow);
        starRepo.save(gregg);
        starRepo.save(bettany);
        starRepo.save(norton);
        starRepo.save(tyler);
        starRepo.save(hurt);
        starRepo.save(cheadle);
        starRepo.save(johansson);
        starRepo.save(rourke);
        starRepo.save(hemsworth);
        starRepo.save(portman);
        starRepo.save(hiddleston);
        starRepo.save(hopkins);
        starRepo.save(skarsgard);
        starRepo.save(dennings);
        starRepo.save(elba);
        starRepo.save(evans);
        starRepo.save(jones);
        starRepo.save(weaving);
        starRepo.save(atwell);
        starRepo.save(stan);
        starRepo.save(ruffalo);
        starRepo.save(renner);
        starRepo.save(jackson);
        starRepo.save(pearce);
        starRepo.save(favreau2);
        starRepo.save(kingsley);
        starRepo.save(pratt);
        starRepo.save(saldana);
        starRepo.save(bautista);
        starRepo.save(diesel);
        starRepo.save(cooper);
        starRepo.save(pace);
        starRepo.save(reily);
        starRepo.save(spader);
        starRepo.save(rudd);
        starRepo.save(lilly);
        starRepo.save(stoll);
        starRepo.save(douglas);
        starRepo.save(mackie);
        starRepo.save(boseman);
        starRepo.save(olsen);
        starRepo.save(holland);
        starRepo.save(cumberbatch);
        starRepo.save(ejiofor);
        starRepo.save(mcadams);
        starRepo.save(wong);
        starRepo.save(mikkelsen);
        starRepo.save(swinton);
        starRepo.save(russell);
        starRepo.save(keaton);
        starRepo.save(zendaya);
        starRepo.save(glover);
        starRepo.save(tomei);
        starRepo.save(blanchett);
        starRepo.save(goldblum);
        starRepo.save(jordan);
        starRepo.save(nyongo);
        starRepo.save(gurira);
        starRepo.save(freeman);
        starRepo.save(whitaker);
        starRepo.save(brolin);
        starRepo.save(pena);
        starRepo.save(pfeiffer);
        starRepo.save(larson);
        starRepo.save(mendelsohn);
        starRepo.save(hounsou);
        starRepo.save(lynch);
        starRepo.save(law);
        starRepo.save(bening);
        starRepo.save(smulders);
        starRepo.save(gyllenhaal);
        starRepo.save(gillan);
        starRepo.save(bibb);
        starRepo.save(toub);
        starRepo.save(tahir);


        Movie ironMan = new Movie("Iron Man", "../images/iron_man.jpg", "https://www.youtube.com/embed/byQpcN78UjQ", favreau, phase1, 2008, 126, "$318,604,126", "Iron Man is the first movie to take place in the Marvel Cinematic Universe.  The story follows Tony Stark, owner of military contracted weapons corporation Stark Industries, and his journey to becoming the first Marvel hero Iron Man.  The movie is directed by Jon Favreau and stars Robert Downey Jr., Terrence Howard, Jeff Bridges and Gwyneth Paltrow. When Marvel Studios announced they were coming out with movies based on Marvel Comics, teenage Allen Haney was beyond excited. As a fan of the Tobey Maguire Spider-Man films I couldn’t wait to see Iron Man. I had never seen any of RDJ’s previous films which allowed me to go in with zero expectations, while others were skeptical based on his past performances and criminal record. He did not disappoint.  RDJ shows he was born for this role.  His ability to become a brilliant billionaire playboy philanthropist is a performance that rivals any lead role in a superhero film before him. Throughout the film you watch him grow as he is faced with life or death situations and the realization that he may be apart of the problem when it comes to war torn countries. By the end of the film Tony Stark becomes the Iron Man and kicks off a 23-movie franchise that spans over a decade long, with still no end in sight.  The film does a great job at paying homage to the comic book character while re-inventing him with modern day technology and world issues. Overall this film is still my favorite Marvel origin story. Re-watching still gives me the same excitement for the MCU I felt back in 2008.", downey, howard, bridges, paltrow, gregg, bettany, favreau2);
        Movie theIncredibleHulk = new Movie("The Incredible Hulk", "../images/incredible_hulk.jpg", "https://www.youtube.com/embed/xbqNb2PFKKA", leterrier, phase1, 2008, 112, "$134,806,913", "The Incredible Hulk is the second installment Marvel Cinematic Universe franchise.  The story follows Bruce Banner, a doctor working in Rio De Janeiro at a soda bottling company.  He is also laying low working to control his emotions and heart rate to avoid turning into the Hulk.  The film is directed by Louis Leterrier and stars Edward Norton, Liv Tyler, Tim Roth and William Hurt.\n Having two Marvel movies in the same year seemed unreal.  We had never had two Batman, Superman or Spider-Man films in the same year.  Although this movie introduced the Hulk Marvel didn’t start the story by explaining why Bruce Banner is the Hulk and it was a great decision.  The viewers know who the Hulk is due to the 2003 film and the television film starring Lou Ferrigno.  Edward Norton was a big name and set big expectations for the film.\n" + "\n" + "The Incredible Hulk lacks the magic that MCU films have.  I believe this is just a sign of growing pains that Marvel experienced when they first started out building a cinematic universe.  The characters Bruce Banner and Thunderbolt Ross are the only things that are relevant to future Marvel movies, which is a big deal because most Marvel movies are intertwined and having hidden easter eggs referencing each other.\n" + "\n" + "As a whole; this is a good movie.  Edward Norton does a great job of portraying Bruce Banner even though his negotiations with Marvel lead to him only playing in this role one time.  Watching this movie gives you the perspective of the internal struggle Banner is dealing with and that is something that does carry through the entire saga.  The greatest thing this film did was have a cut scene that for the first time included two comic book characters from different. Needless to say, it blew my mind." + "\n" + "Having two Marvel movies in the same year seemed unreal.  We had never had two Batman, Superman or Spider-Man films in the same year.  Although this movie introduced the Hulk Marvel didn’t start the story by explaining why Bruce Banner is the Hulk and it was a great decision.  The viewers know who the Hulk is due to the 2003 film and the television film starring Lou Ferrigno.  Edward Norton was a big name and set big expectations for the film.\n" + "\n" + "The Incredible Hulk lacks the magic that MCU films have.  I believe this is just a sign of growing pains that Marvel experienced when they first started out building a cinematic universe.  The characters Bruce Banner and Thunderbolt Ross are the only things that are relevant to future Marvel movies, which is a big deal because most Marvel movies are intertwined and having hidden easter eggs referencing each other.\n" + "\n" + "As a whole; this is a good movie.  Edward Norton does a great job of portraying Bruce Banner even though his negotiations with Marvel lead to him only playing in this role one time.  Watching this movie gives you the perspective of the internal struggle Banner is dealing with and that is something that does carry through the entire saga.  The greatest thing this film did was have a cut scene that for the first time included two comic book characters from different. Needless to say, it blew my mind.", norton, tyler, hurt);
        Movie ironMan2 = new Movie("Iron Man 2", "../images/iron_man_2.jpg", "https://www.youtube.com/embed/BoohRoVA9WQ", favreau, phase1, 2010, 124, "312,433,331", "Iron Man 2 is the first sequel that Marvel produced.  We are blessed with Tony Stark again.  After he revealed his identity at the end of the first movie he is faced with new challenges.  Anton Vanko, who worked with Howard Stark on the arc reactor, has just died and his son Ivan Vanko sees all the attention that Tony Stark is getting as a hero.  Jon Favreau returns as director and stars Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson and Mickey Rourke.\n" + "\n" + "A sequel to a superhero film is something that doesn’t happen often.  And when they do occur it is rare that they satisfy the viewers.  RDJ was the same Tony Stark I knew and love.  Paltrow did an excellent job in her increased role as Tony’s love interest.  But Rourke’s characters as the villain seemed lack luster.  It seemed like a sub plot line when you thought he was the arc reactor technology wielding bad guy.  His first appearance with what seems to be the weapon that will take down Iron Man was the peak of his character.  He took a back seat to other villains like Justin Hammer.  Although Justin Hammer is a good character and it is fun to watch Tony Stark completely own him throughout the film.\n" + "\n" + "It was exciting to see Iron Man back on the big screen and watch the MCU progress forward.  Characters like War Machine and Black Widow make their first appearances and they supported the lead hero by giving the movie a more group feeling.  A feeling that will be utilize in future films to come.\n" + "\n" + "It is nearly impossible for a sequel to overcome the expectations the original creates, and this film fails to do so.  However, it’s still an awesome movie.  RDJ will never be boring to watch as Tony Stark.  Watching multiple superheroes fight side by side was a real treat.\n", downey, paltrow, cheadle, johansson, rourke, jackson, gregg, bettany, favreau2);
        Movie thor = new Movie("Thor", "../images/thor.jpg", "https://www.youtube.com/embed/JOddp-nlNvQ", branagh, phase1, 2011, 115, "181,030,624",  "Thor introduces the first off-world Marvel hero to the MCU.  It follows the hero Thor as he is sent to earth and striped of his power.  Back home his brother Loki tries to take the throne and Thor is unable to return to help until he proves he is worthy.  The movie is directed by Kenneth Branagh and stars Chris Hemsworth, Natalie Portman, Tom Hiddleston and Anthony Hopkins.\n" + "\n" + "Thor is a character I didn’t know much about growing up.  My father was able to tell me all about him as he read the comic books growing up.  It was exciting to go into a Marvel movie with no prior knowledge of the hero.  Hemsworth was a very little-known actor at the time which help the viewer not identify him as any other character decides Thor.  Portman and Hopkins were established actors and their involvement in this film gave the film a feel that it wasn’t just a superhero movie.  Think about it. Award winning Anthony Hopkins dressing up as a Norse god.  If he’s there, this film must mean business.\n" + "\n" + "Thor was able to introduce the idea that not all heroes come from earth without making it seems science fiction.  The characters seemed to be from another world in space which made it seem like they were aliens and the powers they had made sense for that reason.  It’s a good introduction to a new character but isn’t the caliber of film Iron Man was.\n", hemsworth, portman, hiddleston, hopkins, skarsgard, dennings, gregg, elba);
        Movie captainAmerica = new Movie("Captain America: The First Avenger", "../images/captain_america.jpg", "https://www.youtube.com/embed/JerVrbLldXw", johnston, phase1, 2011, 124, "176,654,505",   "Captain America take place during World War II which is the first time an MCU films takes places in a time other than present day.  Steve Rogers is a small young man with a desire to serve his country.  After failing to enlist several times due to his size, he is presented the opportunity to turn himself into exactly what the military is looking for.  The film is directed by Joe Johnston and stars Chris Evans, Tommy Lee Jones, Hugo Weaving, Hayley Atwell and Sebastian Stan.\n" + "\n" + "In their fifth MCU movie Marvel continued with another origin story.  Chris Evans embodies what it means to be a patriot before he is granted the ability to defend his country.  After his transformation you can’t help being marvel at his abilities.  It is satisfying to see someone who is deserving of the gift he is given.  Tommy Lee Jones had a minor role, but it was perfect for him.  Hugo Weaving plays the villain and it was a treat to watch someone with his acting prowess in a Marvel film.  The crossover of superhero and war movie was executed very well.\n" + "\n" + "As far as carrying the universe forward this film did a lot, and the viewer doesn’t even realize it.  Many characters and aspects from this film were used in serval films that came after it.  At the time I was really surprised by how much I enjoyed it.  Looking back, I appreciate it even more for all that it set up for the MCU.\n", evans, atwell, stan, jones, weaving, jackson);
        Movie avengers = new Movie("The Avengers", "../images/avengers.jpg", "https://www.youtube.com/embed/eOrNdBpGMv8", whedon, phase1, 2012, 143, "623,357,910",  "The Avengers is the biggest cross over event of it's time.  Four leading heroes come together to fight a threat that is literally out of this world.  The group struggles to keep their focus on the enemy and instead have their own issues deciding who is best fit to lead the team.  The director is Joss Whedon and the film stars Robert Downey Jr., Chris Evans, Chris Hemsworth, Mark Ruffalo, Scarlett Johansson, Jeremy Renner, Tom Hiddleston and Samuel L Jackson.\n" + "\n" + "In 2012 I attended a Marvel movie marathon that started at noon the day before the release of Marvel's The Avengers.  It included every movie that came before and at midnight we watched Avengers for the first time.  Everyone was stellar.  Seeing heroes on the screen for second time like Hulk, Thor, Captain America was worth the hype.  Bruce Banner was being played by a new actor, Thor seemed to redefine himself as a hero and grow as a character, and Captain America was a soldier trying to get back to civilian life, in a new millennia of course.  They brought the action scenes to the next level.  We got to see Thor fight a lot more than we did in his origin film.  Hulk was a directed warrior instead of a loose cannon.  The greatest scene of all was all six Avengers side by side being lead by Captain America.  Literally the greatest scene in super hero movie history.\n" + "\n" + "Hiddleston is an incredible villain continuing his role as Loki.  The heroes come together and have a historic fight sequence in New York City against an alien army.  The CGI has aged but aged well.  The greatest thing about this movie is that it was the product Marvel Studios was working so hard to create.  A film that took the characters of 4 different stand alone films and putting them together seamlessly.  It's something that had never been accomplished in cinema.  \n" + "\n" + "There is literally nothing I can complain about this movie.  The acting, effects and story were all amazing across the board.  The villain and the idea that threats from outer space could come to earth blew the entire universe wide open.  Nerd's everywhere were speculating what was to come after this film.\n", downey, evans, ruffalo, hemsworth, johansson, renner, hiddleston, gregg, skarsgard, smulders, jackson, paltrow, bettany);
        Movie ironMan3 = new Movie("Iron Man 3", "../images/iron_man_3.jpg", "https://www.youtube.com/embed/YLorLVa95Xo", black, phase2, 2013, 130, "$409,013,994",  "Iron Man 3, the last movie in Marvel's first trilogy.  Tony Stark is back again.  He is making leaps in his technology and is about to make a big break when it comes to his arc reactor.  He and Pepper are officially and item and everything is going well until a terrorist organization calls Tony's bluff and attacks his Malibu home.  Tony must protect what has become most important while saving the world.  Rather than Jon Favreau like before Shane Black directs the film while Robert Downey Jr., Gweneth Paltrow, Don Cheadle, Guy Pearce, Jon Favreau and Ben Kingsley.\n" + "\n" + "With Avengers in the past Iron Man 3 kicks off Phase Two of the MCU.  With a new director it definitely had a different tone that the first two films.  Something that was this film that was lacking in the sequel was Tony Stark smart side.  This movie illustrates that Tony's greatest weapon isn't his suit, it's his brain.  The special effects progress in a way that keeps it fresh.  You never feel like Iron Man is the same old guy fighting bad guys the same way he did in the last 3 movies he had been in.  It's just never boring to watch Tony Stark/ Iron Man on the big screen.\n" + "\n" + "Although this is the third film.  After a great origin movie kicking off the MCU and The Avengers coming out just a year before it was just impossible to live up to the hype.  This is the first time I had actual complaints about a Marvel film.  First is the villain.  There's a big misdirect in this film and in my opinion it took a lot more away from the film than adding to the plot.  There was a direction I thought they were going and frankly, they should have gone that way.\n",downey, paltrow, cheadle, pearce, favreau2, kingsley, bettany);
        Movie thor2 = new Movie("Thor: The Dark World", "../images/thor_2.jpg", "https://www.youtube.com/embed/npvJ9FTgZbM", taylor, phase2, 2013, 112, "206,362,140",  "Thor: The Dark World continues with the adventures of Thor.  Thor is back at Asgard while Loki answers for his war crimes on earth.  The Asgardians learn of the Convergence, a alignment of the Nine realms in approaching.  Jane Foster observes strangle scientific anomalies on earth.  The two of them work together to fight a new ancient threat.\n" + "\n" + "You can almost look at this movie as a sequel to Thor and Avengers.  Loki is the same Loki that was just the enemy of earth a couple movies ago and Thor has come so far since his first film he's almost a different person entirely.  It was fun to see Natalie Portman and her gang working with Thor again.  This movie started to bring humor into the movies in a new way.  Hiddleston is amazing yet again as Loki, delivering a performance that Marvel continues to include in their films.  The ending of this film is one of my favorites as it show cases the relationship of Thor and Loki. \n" + "\n" + "The masses didn't know how to react to this movie.  It kinda jumped head first into a comic book story that the MCU hadn't learned about before.  The villian of the movie are exclusive to this film.  Although this film did contribute a big key to the big picture of the MCU.\n", hemsworth, portman, hiddleston, hopkins, elba, dennings, skarsgard);
        Movie captainAmerica2 = new Movie("Captain America: Winter Soldier", "../images/captain_america_2.jpg", "https://www.youtube.com/embed/7SlILk2WMTI", russo, phase2, 2014, 136, "259,766,572",  "review", evans, jackson, johansson, stan, mackie, smulders);
        Movie guardians = new Movie("Guardians of the Galaxy", "../images/guardians.jpg", "https://www.youtube.com/embed/d96cjJhvlMA", gunn, phase2, 2014, 121, "333,176,600",  "Guardians of the Galaxy is a film about a group of heros with the same name.  Peter Quill is the only human and leader of the team.  He discovers a treasure that gets the attention of powerful forces in the galaxy.  He and his band of misfits must find a way to work together to protect the galaxy from this mystery relec falling into the wrong hands.  The movie is directed by James Gunn and stars Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel, Bradley Cooper, Lee Pace and John C. Reily.\n" + "\n" + "Now this movie was groundbreaking.  The Guardians of the Galaxy comic at this point was hands down the least popular of any other comic Marvel had adapted to film.  And they knock it out of the park.  This movies soundtrack alone is work the price of admission.  The cast is all star and they work so well together to make what I like to call the first super hero comedy.  Chris Pratt has a Han Solo like feel, Gamora is an interesting assasian, Drax is a hilarious tough guy, Rocket is full of one liners and Groot is Groot.  Marvel transformed what a Marvel movie could be with this film and they wouldn't be where they are today without it.\n" + "\n" + "The story is unique because it doesn't include any characters we have seen before.  At the same time it progresses the MCU story by featuring the villains that work closely with THE villain of the whole saga, Thanos.  You can't help but fall in love with this entire film.  It's never a bad idea to rock out with Starlord and the Guardians of the Galaxy.\n", pratt, saldana, bautista, diesel, cooper, pace, reily, gillan);
        Movie avengers2 = new Movie("Avengers: Age of Ultron", "../images/age_of_ultron.jpg", "https://www.youtube.com/embed/tmeOjFno6Do", whedon, phase2, 2015, 141, "459,005,868",  "Avengers: Age of Ultron is the official sequel to the 2012 Avenger film.  The heroes of the first movie are working together to fight a threat that is working on fighting fire with fire.  Tony and Bruce work together to create a weapon that will be able to protect the world from another alien attack, but it comes back to bite them.  Joss Whedon returns to direct along with stars Robert Downey Jr., Chris Evans, Chris Hemsworth, Mark Ruffalo, Scarlett Johansson, Jeremy Renner, Don Cheadle and many many more.\n" + "\n" + "The movie starts with the team working together to infiltrate an enemy base and it couldn't be any better.  It's awesome to see the team working together seamlessly as if they do it everyday.  Just like the first movie the team does have their issues.  There are disagreements and rivalries that will carry for the years to come.  The villain of the movie, Ultron, is  always staying out of the reach of the Avengers.  Since the excitement of seeing all the heroes was captured in the previous Avengers film Ultron is what took this film to the next level.  Marvel is able to recapture that excitement with a villain that at times seemed invincible.  As far as sequels goes it totally delivers.\n" + "\n" + "This movie sets up a lot of what's to come in Phase Three which is what makes these movies so great.  It includes two of the most powerful heroes the MCU has ever scene.  Scarlett Witch and Vision are huge parts of the end of the saga.  It's crazy to think how Marvel plants these seeds all while knowing how much their stories will grow.\n", downey, hemsworth, ruffalo, evans, johansson, renner, spader, jackson, cheadle, olsen, bettany, smulders, mackie, atwell, elba, skarsgard);
        Movie antMan = new Movie("Ant-Man", "../images/ant-man.jpg", "https://www.youtube.com/embed/pWdKf3MneyI", reed, phase2, 2015, 117, "180,202,163",  "Ant-Man caps off Phase Two of the MCU.  Unlike Phase One the Avengers movie wasn't the technical end to this phase.  Ant-man is about former criminal Scott Lang finding himself in the middle of a conflict of scientists.  Hank Pym recruits him to help protect his legacy and stop his shrink suit technology from getting into the wrong hands.  The films director is Peyton Reed and stars Paul Rudd, Evangeline Lilly, Corey Stoll and Michael Douglas.\n" + "\n" + "As far as Marvel movies go this film seems to have little to do with the MCU.  It's a great stand alone movie.  Paul Rudd is hilarious and the movies creators do an amazing job at making Ant-Man not only a real hero but one that has some of the coolest powers you've ever seen.  On the surface it seems like all he can do it shrink down but that ability makes him an amazing hand to hand fighter and makes for dramatic and historical fight sequences.\n" + "\n" + "Without the Marvel trademark this movie would fall under the category of comedy but it's a super hero movie nonetheless.  But with that Marvel trademark and the continued star power talent they can draw in they made another fun and successful film.\n", rudd, douglas, lilly, stoll, mackie, pena, atwell);
        Movie captainAmerica3 = new Movie("Captain America: Civil War", "../images/civil war.jpg", "https://www.youtube.com/embed/dKrVegVI0Us", russo, phase3, 2016, 147, "408,084,349",  "Captain America: Civil War is the last movie in the trilogy.  The US government is writing legislation to real in the heroes and their ability to respond to situations in an attempt to lessen the collateral damage they have caused in the past.  This creates a divide in the Avengers that a secret villain takes advantage of.  The Russo brothers make their Marvel debut as Anthony and Joe Russo direct and Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan, Anthony Mackie, Don Cheadle, Jeremy Renner, Chadwick Boseman, Paul Bettany, Elizabeth Olsen, Paul Rudd and Tom Holland.\n" + "\n" + "As you can tell by the cast list this is basically a mini Avengers movie.  The tensions between the team are at an all time high and something from the past pushes them to the edge.  The villain of the movie is almost the heroes themselves as they find themselves throwing punches at each other multiple times.  Of course this movie also introduces Spider-Man for the first time in the MCU.  Something fans like me had been waiting years for.  The acting is top notch.  Chris Evans and RDJ do a great job transitioning their bickering into an all out emotional civil war.\n" + "\n" + "This is hands down the greatest non-Avengers MCU film in my opinion.  It's kind of cheating by including not only four of the original Avengers but five new Avengers.\n", evans, downey, johansson, stan, mackie, cheadle, renner, boseman, bettany, olsen, rudd, holland, hurt, freeman, tomei);
        Movie doctorStrange = new Movie("Doctor Strange", "../images/doctor_strange.jpg", "https://www.youtube.com/embed/HSzx-zryEgM", derrickson, phase3, 2016, 115, "232,641,920",  "Doctor Strange is another origin film for a new Marvel hero.  Dr. Stephen Strange is a high profile surgeon that is left with nerve damage in his hands after a bad car accident.  The nerves seem to be beyond repair and he is no longer able to practice surgery.  Dr. Strange will stop at nothing to get his hands back, and one method leads him down a rabbit hole he wasn't expecting.  Scott Derrickson directs while the film stars Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Benedict Wong, Michael Stuhlbarg and Tilda Swinton.\n" + "\n" + "Doctor Strange's character starts out like a Tony Stark.  He's a brilliant mind with lots of money and a huge ego.  After his accident is seems that his life is taken away from him and he is forced to take a step back and look at the person he really is.  The ancient one played by Tilda Swinton does a good job and being his Mr. Miyagi and showing him how to perfect his new powers.  This movie introduces new forms of powers and magic we haven't seen before and that's exciting.  It's a great origin story of a character that will become a huge part of this phase of the MCU.\n" + "\n" + "Overall I enjoyed Doctor Strange.  It doesn't come to mind when I think of my favorite Marvel films but it has so much acting talent it's hard to find things to complain about.  It is a perfect example of how far origin films have come since the days of Thor when it comes to CGI.\n", cumberbatch, ejiofor, mcadams, wong, swinton, mikkelsen);
        Movie guardians2 = new Movie("Guardians of the Galaxy Vol 2", "../images/guardians_vol2.jpg", "https://www.youtube.com/embed/wUn05hdkhjM", gunn, phase3, 2017, 136, "389,813,101",  "Guardians of the Galaxy Vol. 2 is the sequel to the first movie with the same name.  The gang is back together but this time thy're facing a new threat.  Peter Quill is suprised to meet his long lost father, but not all is well when they visit his home planet.  The team must face diversity when the intentions of Quills father come into question.  James Gunn returns to direct as well as starring actors Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel, Bradley Cooper and Kurt Russell.\n" + "\n" + "This film is the rare case of a sequel out doing it's original.  The cast comes back in an opening scene that is an instant classic.  The soundtrack is just as good as the first, the jokes are funnier, and most important of all the characters develop.  For a team of aliens they all seem to become more human in this film.  Starlord breaks out as my personal favorite and his story is given the attention it deserved.  Gamora is given depth and she's no longer just an assassin.  Drax, the character that takes everything literally is made softer as a grieving father.  Groot is reborn and Rocket as well is soften into a furry friend to the other Guardians.\n" + "\n" + "You can't go wrong with a Guardians movie.  If I was going to sit down and watch one it would definitely be Vol 2.  It lacks much advancing of the MCU but makes huge progress for the Guardians themselves.\n", pratt, saldana, bautista, diesel, cooper, russell, gillan);
        Movie spiderMan = new Movie("Spider-Man: Homecoming", "../images/spider-man_homecoming.jpg", "https://www.youtube.com/embed/39udgGPyYMg", watts, phase3, 2017, 133, "334,201,140",  "Spider-Man Homecoming is the first movie dedicated to Peter Parker in the MCU.  High schooler Peter Parker already has experience not only keeping his neighborhood safe but fighting along side Avengers like Iron Man.  He's excited to get more experience working with Tony Stark but needs to be reminded he is a kid in school.  And being a kid in school isn't easy.  Jon Watts directs the film that stars Tom Holland, Michael Keaton, Jon Favreau, Gwyneth Paltrow, Zendaya, Donald Glover, Marisa Tomei and Robert Downey Jr.\n" + "\n" + "Spider-Man was always my favorite super hero growing up.  The Tobey Maguire movies were my first experience with heroes on the big screen and I fell in love.  Tom Holland was the perfect pick for this role.  He's never had another major role so it was easy to immediately think of him as Peter Parker.  His chemistry with RDJ on screen is what really puts the movie over the top.  The overall feel of the movie is similar to that of the Phase Two films.  It has a serious tone but sneaks in a lot of great funny moments without taking away from what is a stake.\n" + "\n" + "Marvel reels in another powerhouse talent in Michael Keaton.  I mean, they got Batman to play a bad guy in a Marvel movie.  And he is sinister.  That mans smile never lets you settle down and get comfortable.  He convinces you he's capable of anything and follows up in his performance.  RDJ has a great cameo in the movie that only adds to the quality of the film and never takes away form the fact that this is Spider-Man's show.\n" + "\n" + "I can't explain how excited I was that Spider-Man finally made it into the MCU.  Tom Holland and this cast did not disappoint in the least.\n", holland, keaton, downey, tomei, favreau2, paltrow, zendaya, glover);
        Movie thor3 = new Movie("Thor: Ragnarok", "../images/thor_3.jpg", "https://www.youtube.com/embed/ue80QwXMRHg", waititi, phase3, 2017, 130, "$315,058,289",  "Thor Ragnarok is the third installment in the Thor saga.  Thor returns to Asgard only to find Loki posing as Odin and his father no where to be found.  After Loki reveals he sent Odin to earth they find him there only to watch him pass away moments later.  Odin's death means Thor's sister Hela will return to take the throne at Asgard.  Thor and Loki team up with an old friend to save Asgard from her reign.  Taika Waititi directs and the movie stars Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Idris Elba, Jeff Goldblum, Anthony Hopkins and Mark Ruffalo.\n" + "\n" + "I've got to say other than Iron Man three, the best marvel films seem to come around the third time.  Captain America Civil War and now Thor Ragnarok.  The Marvel Comedy feel like Guardians reinvented is prevalent in this movie as it mostly takes place on other worlds.  The best part is that Marvel continued their trend of including other Avengers in solo films by putting the Hulk in Thor's third movie.  They have a duel and it's one of the best the MCU has ever created.  I almost forgot, the soundtrack rivals that of the Guardians as well.  My personal favorite part of this movie is Korg, a new hilarious ally of Thor.\n" + "\n" + "Phase Three is where Marvel found their wheelhouse and this film show cases everything that is great about Marvel films.  From the all-star cast, the soundtrack, the action and comedy.  It's the full package; a Marvel Classic.\n", hemsworth, hiddleston, blanchett, elba, goldblum, ruffalo, hopkins, cumberbatch);
        Movie blackPanther = new Movie("Black Panther", "../images/black panther.jpg", "https://www.youtube.com/embed/xjDjIWPwcPU", coogler, phase3, 2018, 134, "700,059,566",  "Black Panther is yet another origin story for a beloved Marvel hero.  T'Challa is the Black Panther and King of Wakanda.  there country in Africa is seen as a third world country, when in reality it is far more advanced than any other country on earth.  Their vibranium technology is something wars have been fought over and many have died for.  Conflict arises when a long lost cousin of T'Challa comes forward and challenges him for the throne.  The movie is directed by Ryan Coogler and stars Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira, Martin Freeman and Forest Whitaker.\n" + "\n" + "I don't have to tell you the hype that was around this movie.  After T'Challa's appearance in Civil War the audience was dying to see a Black Panther film, myself included.  This movie takes us tot he beautiful world of Wakanda and introduces us to the game changing medal of vibranium.  Marvel does a great job of giving Black Panthers suit new features that we haven't seen before.  It separates his abilities from the rest.  Boseman does a great job at portraying an honorable man that understand the responsibility that comes with being not only a king but the defender of a country.  It contrasts greatly to the origins of Iron Man and Thor, who are heroes that needed to better themselves in order to be seen as a hero.  T'Challa is that man from the beginning.\n" + "\n" + "Michael B. Jordan however steals the show.  His characters story is one that you sympathize with.  There are points in the movie where you know what he is saying is wrong but you understand where he is coming from.  As the villain he is able to make the audience question who they are rooting for.  There's not wonder this film is the fourth highest grossing movie of all time.\n" + "\n" + "This movie is easily in my Top 5 Marvel Movies.  Once again Marvel creates an excellent hero origin story with an amazing cast, stellar soundtrack and remarkable cinematography.\n", boseman, jordan, nyongo, gurira, freeman, whitaker);
        Movie avengers3 = new Movie("Avengers: Infinity War", "../images/avengers_infinity_war.jpg", "https://www.youtube.com/embed/6ZfuNTqbHE8", russo, phase3, 2018, 160, "678,815,482",  "Avengers Infinity War is the third movie in the Avengers Saga.  The threat is here.  Thanos is done hiding in the shadows controlling the puppets.  It's time to take care of it himself.  The team for the first time is not together.  The wounds from the events of Civil War are still fresh and the team aren't on speaking terms.  This only makes it easier for Thanos to start collecting stones on his way to correcting this universe. The Russo brothers return to direct and with them the stars Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson, Benedict Cumberbatch, Don Cheadle, Tom Holland, Chadwick Boseman, Elizabeeth Olsen, Anthony Mackie, Sebastian Stan, Dave Bautista, Zoe Saldana, Josh Brolin and Chris Pratt.\n" + "\n" + "The fact that the last person listed is Chris Pratt should tell you all you need to know about this film.  The single largest crossover film of all time.  Characters from eight different films are brought together to fight one common enemy.  This film starts off illustating the true power of Thanos and clear sets the stakes at a new level.  The entire universe is at stake and the Russo brothers never let you forget.\n" + "\n" + "Josh Brolin is finally given the screen time Thanos deserves and he takes advantage of every second.  His performance never once reminded me that is was Josh Brolin behind that purple giant.  For the first time the heroes were losing.  The movie has your heart racing from the very beginning and you find yourself on a roller-coaster of emotions.  The heroes constantly take one step foward and two steps back.\n" + "\n" + "At the time of release this was my favorite Marvel movie yet.  It had everything.  Including something no other Marvel movie had to this point.  It left me not wanting more but needing more.\n", downey, hemsworth, ruffalo, evans, johansson, cheadle, cumberbatch, holland, boseman, saldana, hiddleston, bettany, olsen, mackie, stan, elba, gurira, wong, bautista, diesel, cooper, paltrow, brolin, pratt, hurt, gillan);
        Movie antMan2 = new Movie("Ant-Man and the Wasp", "../images/ant-man_the-wasp.jpg", "https://www.youtube.com/embed/UUkn-enk2RU", reed, phase3, 2018, 125, "216,648,740",  "Ant-Man and the Wasp is the sequel to Ant-Man.  Taking place before the events of Infinity War Scott Lang is on house arrest for his participation in the events of Civil War.  Although he is forbidden from leaving his home Hank Pym and his daughter Hope are in need of his help again.  They help him escape his own home and fill him in on the quantum realm and why they need to go there.  Directed by Peyton Reed and starring Paul Rudd, Evangeline Lilly, Michael Pena, Walton Goggins, Bobby Cannavale, Judy Greer, Michelle Pfeiffer and Michael Douglas.\n" + "\n" + "Another Ant-Man movie and another Marvel Comedy.  Paul Rudd continues to be a lovable hero and his friends continue to bring a smile to my face.  It has a lot of the same feel as the first Ant-Man and in every right way.  It's hilarious.  The major difference is that this film did a lot more for the MCU than the first one did.  The introduction to the quantum realm is similar to Black Panthers introduction to vibranium.  They both take the MCU to the next level.  The most important thing this movie did was in it's cut scene.  It leads the viewers perfectly into the fourth Avengers movie that was to come and allowed the nerds to speculate to their hearts desire.\n" + "\n" + "This movie is what is it.  It's a great comedy that takes place within the MCU.  It's not on the same level as an Avenger film but it holds up to the same standard Marvel has created for themselves in Phase Three.\n", rudd, lilly, pena, pfeiffer, douglas);
        Movie captainMarvel = new Movie("Captain Marvel", "../images/captain_marvel.jpg", "https://www.youtube.com/embed/Z1BCujX3pw8", boden, phase3, 2019, 125, "426,829,839",  "Captain Marvel is the second MCU film to take place in the past.  Vers is a member of an elite squad known as Starforce.  She has abilities that aren't quite known that make her an excellent advocate for justice.  She finds herself crashed on planet earth in the early 90s.  While she attempts to find her way home she finds out more about her past and even something more about the leader of her team.  Co-directed by Anna Boden and Ryan Fleck. Starring Brie Larson, Samuel L Jackson, Ben Mendelsohn, Djimon Hounsou, Lee Pace, Lashana Lynch, Jude Law and Annette Bening.\n" + "\n" + "Captain Marvel is yet another origin story to introduce a new hero.  The 90s theme is something we haven't seen before in a Marvel film and was refreshing to see characters we love in a different time.  Going in I didn't know much about the character which made the movie a kind of a mystery mixed with a episode of Law and Order.  I found myself trying to figure out what was really going on with Captain Marvel and who the bad guys really were.\n" + "\n" + "The movie overall has a serious tone.  It did well at including comedy like they always do but you never forgot what was at stake.  Brie Larson, an Oscar winner, is great as a lead Marvel hero.  I left the movie wanting to know even more about her back story.  I felt that we only got half of why she is who she is.  But that's the great thing about Marvel Movies.  They always leave you wanting more.\n", larson, jackson, mendelsohn, law, bening, hounsou, pace, lynch);
        Movie avengers4 = new Movie("Avengers: Endgame", "../images/endgame.jpg", "https://www.youtube.com/embed/TcMBFSGVi1c", russo, phase3, 2019, 182, "858,373,000",  "Avengers Endgame is the fourth movie in the Avengers Saga and bigger than ever before.  The movies takes place five years after the events of Infinity War and the heroes are defeated to say the least.  They are separated.  They are upset.  They are grieving.  They come together to find Thanos and figure out a way to reverse the tragedy that occurred five years ago.  The Russo brothers return to direct and with them the stars Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson, Benedict Cumberbatch, Don Cheadle, Tom Holland, Chadwick Boseman, Brie Larson, Elizabeeth Olsen, Anthony Mackie, Sebastian Stan, Dave Bautista, Zoe Saldana, Josh Brolin and Chris Pratt.\n" + "\n" + "Here we go again.  Just one year after the largest crossover event were adding yet another hero to the mix to make it nine films worth of characters coming together.  This movie is truly an homage to the entire collection of MCU films.  There are constant reminders of the events of the past.  Chris Evans and RDJ work over all these years has come down to this.  The two of them are perfect on screen together.  The weight that is on each of their shoulders can be felt throughout the entire film.  You'll laugh, you'll cry.  You'll enjoy the most rewarding movie watching experience of all time after watching 22 films over 11 years.\n" + "\n" + "There truly couldn't have been a better way to end such an amazing Saga.  22 movies that tie together so well finally coming to a close.  I truly don't know if they'll be able to do it again.", downey, evans, ruffalo, hemsworth, johansson, renner, cheadle, rudd, cumberbatch, boseman, larson, holland, saldana, lilly, olsen, mackie, stan, hiddleston, gurira, wong, bautista, swinton, favreau2, atwell, portman, tomei, douglas, pfeiffer, hurt, smulders, diesel, cooper, paltrow, brolin, pratt, jackson, gillan);
        Movie spiderMan2 = new Movie("Spider-Man: Far From Home", "../images/spider-man_far_from_home.jpg", "https://www.youtube.com/embed/LFoz8ZJWmPs", watts, phase3, 2019, 140, "390,532,085",  "Coming Soon!", holland, jackson, gyllenhaal, tomei, favreau2, zendaya);
        Movie blackWidow = new Movie("Black Widow", "../images/black_widow.jpg", "https://www.youtube.com/embed/ybji16u608U", shortland, phase3, 2020, 0, "$0",  "Coming Soon!", johansson, hurt);
        movieRepo.save(ironMan);
        movieRepo.save(theIncredibleHulk);
        movieRepo.save(ironMan2);
        movieRepo.save(thor);
        movieRepo.save(captainAmerica);
        movieRepo.save(avengers);
        movieRepo.save(ironMan3);
        movieRepo.save(thor2);
        movieRepo.save(captainAmerica2);
        movieRepo.save(guardians);
        movieRepo.save(avengers2);
        movieRepo.save(antMan);
        movieRepo.save(captainAmerica3);
        movieRepo.save(doctorStrange);
        movieRepo.save(guardians2);
        movieRepo.save(spiderMan);
        movieRepo.save(thor3);
        movieRepo.save(blackPanther);
        movieRepo.save(avengers3);
        movieRepo.save(antMan2);
        movieRepo.save(captainMarvel);
        movieRepo.save(avengers4);
        movieRepo.save(spiderMan2);
        movieRepo.save(blackWidow);
    }
}
